### ISSUE TITLE
Lobby STILL not working [BUG] 

### ISSUE THREAD

**Issue by RaliiTheAvali** [Zingabopp/MultiplayerExtensions#124]
**Multiplayer Extensions Version and Download Source**

**Your Platform**
PC/Steam/Oculus store.

**Describe the bug**
Lobby bug is NOT resolved. just updated to the  'latest release' and after each song it still goes back to a main menu like screen and unable to start another song without restarting the lobby.

**To Reproduce**
Complete a song in online mode

**Expected behavior**
Should return to the multiplayer screen

**Log**
[_latest.log](https://github.com/Zingabopp/MultiplayerExtensions/files/6566986/_latest.log)

**Screenshots/Video**
See Closed bug report for a similar screen shot 

**Additional context**
Previous issue was not confirmed by MULTIPLE ppl to be resolved.

**Comment by Goobwabber** [comment]
"latest release" is only the latest *public* release. if I resolve an issue, it's because I fixed it in a development build - which you can access [here](https://github.com/Zingabopp/MultiplayerExtensions/actions?query=workflow%3ABuild+branch%3Amaster) by clicking a build and then searching for the file under "artifacts".

**Comment by RaliiTheAvali** [comment]
Testing***

**Comment by Goobwabber** [comment]
Also people tested this version on #103

**Comment by RaliiTheAvali** [comment]
Seems to be stable,  helped me learn something new bout github aswell, i musta over looked the test builds.
