### ISSUE TITLE
Notes getting weird

### ISSUE THREAD

**Issue by LedgendODST** [Zingabopp/MultiplayerExtensions#22]
Hello, 

i started Playing with my Friends and after like 2 hours i had a issue (i don't really know from which Plugin the problem comes from but maybe keep an eyes on the problem) i know this is a Beta and i really want to help you out to report every problem i get and i really hope you accept it.

Logs and a picture of my Plugins and also a Bug Video here. 

but i got it on every song!

https://www.youtube.com/watch?v=ujVNJ8LDKyE&feature=youtu.be

https://prnt.sc/vawkb5
[Logs.zip](https://github.com/Zingabopp/MultiplayerExtensions/files/5469811/Logs.zip)

Detected in Version : MultiplayerExtensions-0.1.2-bs1.12.2-c96e54d

to see the diffrent there is a working version on BS : 1.11.0

https://www.youtube.com/watch?v=bb2jd0Alq1A

**Comment by Zingabopp** [comment]
I'm fairly certain that isn't a problem with MultiplayerExtensions, it doesn't have any code that touches notes or hit detection to my knowledge. It could be ScoreSaber, since it's throwing exceptions that appear to be related to the [replay] Recorder, which has a much higher chance of being the problem (although I haven't personally experienced weird missed notes like that and have seen those ScoreSaber exceptions as well, so maybe not).

**Comment by LedgendODST** [comment]
uuuhhh should i report that problem to the ScoreSaber Github? with saying that i was using MultiplayerExtensions?
or what you recommend doing rn?

**Comment by Zingabopp** [comment]
I already messaged Umby about it.

**Comment by LedgendODST** [comment]
aye thank you very much!

**Comment by TwinkieShip** [comment]
I had the same problem but much worse
My experience with it was any map that was using custom extensions bugged out like this and was impossible to play with others. Playing the map alone in the multiplayer with others spectating was perfectly fine but only seems to happen when there are others playing it as if the notes from the other players + delay came onto my side but not hitable

**Comment by Goobwabber** [comment]
stale and seems like its not an issue with mpex
