### ISSUE TITLE
[BUG] Infinite "Loading.." text when starting the game

### ISSUE THREAD

**Issue by krefang** [Zingabopp/MultiplayerExtensions#70]
**Your Platform**
PC, Steam

**Describe the bug**
When starting the game, an infinite "Loading.." text appears with a spinning ring under the image of selected song. This happens every time and even if i already have the selected song. When someone selects a song i don't have, most of the time there will be "Loading.." instead of a name of the song on the player list.

**To Reproduce**
1. Join a multiplayer server
2. Wait for the game to start
3. Watch the infinite loading untill the host shuts down the server

**Expected behavior**
The game should've started, especially when i already had the selected song installed.

**Log**
[_latest.log](https://github.com/Zingabopp/MultiplayerExtensions/files/5736789/_latest.log)

[_latest.log](https://github.com/Zingabopp/MultiplayerExtensions/files/5736790/_latest.log) - this is the log of a session where i took the screenshots below

**Screenshots/Video**
![20201223221504_1](https://user-images.githubusercontent.com/74023957/103030997-022aa380-456e-11eb-900b-d8d8e5f1826b.jpg)
![20201223221520_1](https://user-images.githubusercontent.com/74023957/103031000-048cfd80-456e-11eb-9612-e45635df0030.jpg)
As can be seen, the game won't start and display an infinite "loading.." text even though i have the selected song installed.

**Additional context**
none

**Comment by Joreon** [comment]
Same problem here!

**Comment by pg98** [comment]
This is probably because you have MultiplayerExtensions 0.4.0 (which is still work in progress) while the other player has MultiplayerExtensions 0.3.0. 
Try downloading the latest build of 0.3.0 from the link in the "Installation" section of the readme (https://github.com/Zingabopp/MultiplayerExtensions#installation). Direct link to the downloads: [Here](https://github.com/Zingabopp/MultiplayerExtensions/actions?query=workflow%3ABuild+branch%3Amaster)

Clicking on the "Artifacts" tab at the top will show all branches of the repository so it will include the 0.4.0 builds, while the link in the readme only shows builds on the `master` branch (which contains version 0.3.0).

**Comment by krefang** [comment]
Yep, installing 0.3.0. fixed the issue, thanks!
